### ISSUE TITLE
Error: Module S3Filesystem could not be found and loaded

### ISSUE THREAD

**Issue by ianmjones** [polevaultweb/s3-filesystem#2]
Full error message:

```
[Codeception\Exception\ConfigurationException]     
  Module S3Filesystem could not be found and loaded
```

This happens on case sensitive filesystems, but not on case insensitive systems.

PR coming ...

**Comment by ViMac2610** [comment]
Hi team, 
I still see the error message when I run the build 
`Module S3Filesystem could not be found and loaded `
